name: Code Quality Check  # The name of the GitHub Actions workflow

on: [push, pull_request]  # Workflow triggered on code push and pull request events

jobs:
  flake8:  # Define a job named "flake8"
    name: Run Flake8  # Job name
    runs-on: ubuntu-latest  # Job runs on the latest version of Ubuntu

    steps:  # List of steps within the job
      - name: Checkout code  # Step to check out the code
        uses: actions/checkout@v2  # Use GitHub Action to fetch the code

      - name: Set up Python  # Step to set up the Python environment
        uses: actions/setup-python@v2  # Use GitHub Action to set up Python
        with:
          python-version: 3.11  # Specify the Python version to use (e.g., 3.8)

      - name: Install dependencies  # Step to install necessary dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install flake8  # Install Flake8 using pip

      - name: Run Flake8  # Step to run the Flake8 tool
        run: |
          flake8 .  # Check all Python files in the current directory for PEP 8 compliance

      - name: Block push on failure
        if: failure()  # This step will only run if the previous step fails
        run: echo "Flake8 check failed. Blocking the push." && exit 1

  docstring_check:
    name: Check Docstrings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Replace 'x' with your desired Python version

      - name: Install pydocstyle
        run: pip install pydocstyle

      - name: Run docstring checks
        run: python check_docstrings.py

      - name: Block push on failure
        if: failure()  # This step will only run if the previous step fails  
        run: echo "Check Docstrings check failed. Blocking the push." && exit 1

  unittest:
    name: Run Python Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Set your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Install project dependencies (if any)

      - name: Run unit tests
        run: python -m unittest discover tests